# Originally implemented by Christian Fetzer
# on https://cc-github.bmwgroup.net/mci/jc7cloud
---
- name: restart samba services
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - smbd
    - nmbd
